### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'Object'

### ISSUE THREAD

**Issue by DavidNguyen-android** [mithunadhikari40/pretty_http_logger#4]
I got Unhandled Exception: type 'Null' is not a subtype of type 'Object' when post data with value null. 
{
    "organizationID": null
}

**Comment by midoshawky** [comment]
i faced this also its just because function param not nullable 

open logger. dart or click on the exception form the logs will send u to line 292 just make Object nullable Object?

```
void _printKV(String key, Object? v) {
    final pre = '╟ $key: ';
    final msg = v.toString();

    if (pre.length + msg.length > maxWidth) {
      logPrint(pre);
      _printBlock(msg);
    } else {
      logPrint('$pre$msg');
    }
  }
```

**Comment by mithunadhikari40** [comment]
Closed in favor of https://github.com/mithunadhikari40/pretty_http_logger/pull/5
